# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy jar
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o 'StrictHostKeyChecking=no' -i ~/.ssh/id_rsa ./target/situation-puzzle-0.0.1-SNAPSHOT.jar $USERNAME@$HOSTNAME:/home/$USERNAME/app.jar
        ssh -o 'StrictHostKeyChecking=no' -i ~/.ssh/id_rsa $USERNAME@HOSTNAME "bash /home/$USERNAME/deploy.sh"
